version: '3.8'

services:
  app:
    container_name: cash-compass-app
    build: .
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src  # Mounts the source directory to the container
      - ./pom.xml:/app/pom.xml  # Ensures changes to pom.xml are also reflected

  db:
    container_name: cash-compass-postgresql
    image: postgres:16
    environment:
      POSTGRES_DB: financingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: cash-compass-redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: